name: my_monitor_example
description: Example app for my_monitor package
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_performance_monitor:
    path: ../
